version: "3"

services:
  web:
    build:
      dockerfile: ./_docker/nginx/Dockerfile
    volumes:
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8877:80"
    depends_on:
      - app
    container_name: nginx_app
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
#    environment:
#      MYSQL_HOST: db
#      MYSQL_PORT: ${MYSQL_PORT}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#    depends_on:
#      - db
    container_name: php_app
#  db:
#    image: mysql:8.0
#    restart: unless-stopped
#    volumes:
#      - mysqldata:/var/lib/mysql
#    environment:
#      MYSQL_HOST: db
#      MYSQL_PORT: ${MYSQL_PORT}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
##    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
#    container_name: php_db
#
#volumes:
#  mysqldata:
